#:schema https://raw.githubusercontent.com/cloudflare/workers-sdk/main/packages/wrangler/config-schema.json
name = "blog-hub"
compatibility_date = "2026-04-20"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[assets]
directory = "./dist"

[vars]
# Add environment variables here
